# @name 微博超话签到所需参数获取
# @version v1.1.0

# mitm
hostname = api.weibo.cn, mapi.weibo.com

# 获取微博超话签到需要的各项参数
^https?://m?api\.weibo\.c(n|om)\/2\/push url script-request-header https://raw.githubusercontent.com/axtyet/ios/main/ios_tasks_rule/weibotalk.cookie.js
